// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post-service.proto

package post_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64                `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string               `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               int64                `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string               `protobuf:"bytes,5,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string               `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Product              string               `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string               `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string               `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64              `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string               `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo             `protobuf:"bytes,12,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32                `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            *timestamp.Timestamp `protobuf:"bytes,15,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Post) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Post) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Post) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Post) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *Post) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Post) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Post) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *Post) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Post) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Post) GetUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedOn
	}
	return nil
}

type Photo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{1}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Photo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreatePostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string   `protobuf:"bytes,5,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Product              string   `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string   `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64  `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string   `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,12,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,14,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{2}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePostRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *CreatePostRequest) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *CreatePostRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreatePostRequest) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *CreatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePostRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *CreatePostRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreatePostRequest) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *CreatePostRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreatePostRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *CreatePostRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *CreatePostRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreatePostRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type CreatePostResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Error                bool     `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{3}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePostResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type UpdatePostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string   `protobuf:"bytes,5,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Product              string   `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string   `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64  `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string   `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,12,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,14,opt,name=api,proto3" json:"api,omitempty"`
	DbId                 string   `protobuf:"bytes,15,opt,name=dbId,proto3" json:"dbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{4}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *UpdatePostRequest) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *UpdatePostRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdatePostRequest) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *UpdatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdatePostRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *UpdatePostRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdatePostRequest) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *UpdatePostRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdatePostRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *UpdatePostRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *UpdatePostRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePostRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

type UpdatePostResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Error                bool     `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{5}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func init() {
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*Photo)(nil), "Photo")
	proto.RegisterType((*CreatePostRequest)(nil), "CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "CreatePostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "UpdatePostResponse")
}

func init() { proto.RegisterFile("post-service.proto", fileDescriptor_3d05c9fd6a018b85) }

var fileDescriptor_3d05c9fd6a018b85 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x95, 0x41, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x35, 0x71, 0x92, 0xd6, 0x2f, 0xa5, 0x4d, 0xa7, 0x11, 0x1a, 0x45, 0x15, 0x58, 0x5e,
	0x99, 0x4a, 0xd8, 0x22, 0x6c, 0x50, 0xb7, 0xac, 0xba, 0x81, 0x32, 0xc0, 0x01, 0x1c, 0x7b, 0x9a,
	0x5a, 0x4a, 0x3c, 0xc3, 0xcc, 0xb8, 0x07, 0x80, 0x23, 0x70, 0x14, 0xae, 0xc0, 0x0d, 0xb8, 0x02,
	0x7b, 0xae, 0x80, 0xe6, 0x8d, 0x9d, 0x04, 0x19, 0x89, 0x0d, 0xb0, 0xea, 0xee, 0xfd, 0xff, 0xbc,
	0x37, 0xf6, 0xf3, 0xf7, 0x3c, 0x03, 0x54, 0x49, 0x63, 0x9f, 0x1a, 0xa1, 0xef, 0xaa, 0x42, 0xa4,
	0x4a, 0x4b, 0x2b, 0xe7, 0x8f, 0x57, 0x52, 0xae, 0xd6, 0x22, 0x43, 0xb5, 0x6c, 0x6e, 0x32, 0x5b,
	0x6d, 0x84, 0xb1, 0xf9, 0x46, 0xb5, 0x09, 0xe7, 0x6d, 0x42, 0xae, 0xaa, 0x2c, 0xaf, 0x6b, 0x69,
	0x73, 0x5b, 0xc9, 0xda, 0xf8, 0xd5, 0xf8, 0x6b, 0x00, 0xc3, 0x6b, 0x69, 0x2c, 0x3d, 0x86, 0x41,
	0x55, 0x32, 0x12, 0x91, 0x24, 0xe0, 0x83, 0xaa, 0xa4, 0x8f, 0x00, 0x8a, 0xc6, 0x58, 0xb9, 0x11,
	0xfa, 0xaa, 0x64, 0x03, 0xf4, 0xf7, 0x1c, 0x1a, 0xc3, 0x51, 0xa7, 0x5e, 0xe5, 0x1b, 0xc1, 0x82,
	0x88, 0x24, 0x21, 0xff, 0xc5, 0xa3, 0x0f, 0x61, 0xdc, 0x18, 0xac, 0x1f, 0x62, 0x7d, 0xab, 0x9c,
	0x5f, 0xdc, 0xe6, 0xb5, 0x58, 0xb3, 0x11, 0x56, 0xb5, 0x8a, 0x46, 0x30, 0x29, 0x85, 0x29, 0x74,
	0xa5, 0xdc, 0x2b, 0xb2, 0x31, 0x2e, 0xee, 0x5b, 0x94, 0xc1, 0x81, 0xd2, 0xb2, 0x6c, 0x0a, 0xcb,
	0x0e, 0x70, 0xb5, 0x93, 0x74, 0x06, 0x23, 0x75, 0x2b, 0x6b, 0xc1, 0x0e, 0xd1, 0xf7, 0x82, 0x4e,
	0x21, 0x50, 0x55, 0xc1, 0x42, 0xf4, 0x5c, 0x88, 0x79, 0xba, 0x2a, 0x04, 0x83, 0x88, 0x24, 0x84,
	0x7b, 0xe1, 0xdc, 0x5a, 0x5a, 0x61, 0xd8, 0xc4, 0x57, 0xa3, 0xa0, 0xe7, 0xb8, 0xa7, 0x95, 0xec,
	0x28, 0x0a, 0x92, 0xc9, 0x62, 0x9c, 0x5e, 0x3b, 0xc5, 0xbd, 0xe9, 0xba, 0x30, 0x36, 0xb7, 0x8d,
	0x61, 0x0f, 0x22, 0x92, 0x8c, 0x78, 0xab, 0xe8, 0x0b, 0x08, 0x0b, 0x2d, 0x72, 0x2b, 0xca, 0xd7,
	0x35, 0x3b, 0x8e, 0x48, 0x32, 0x59, 0xcc, 0x53, 0x0f, 0x21, 0xed, 0x28, 0xa5, 0xef, 0x3a, 0x4a,
	0x7c, 0x97, 0xec, 0x2a, 0x1b, 0x55, 0xb6, 0x95, 0x27, 0x7f, 0xae, 0xdc, 0x26, 0xc7, 0x4f, 0x60,
	0x84, 0xef, 0xd6, 0xc3, 0x38, 0x85, 0xa0, 0xd1, 0x6b, 0xe4, 0x17, 0x72, 0x17, 0xc6, 0x3f, 0x06,
	0x70, 0xfa, 0x12, 0x1f, 0xe9, 0xb8, 0x73, 0xf1, 0xa1, 0x11, 0xf7, 0xf8, 0xff, 0x22, 0xfe, 0x29,
	0x04, 0xb9, 0xaa, 0x10, 0x7c, 0xc8, 0x5d, 0x18, 0xdf, 0x00, 0xdd, 0xff, 0xe0, 0x46, 0xc9, 0xda,
	0x88, 0x2e, 0x8f, 0x6c, 0xf3, 0x5c, 0x77, 0x1b, 0x61, 0x4c, 0xbe, 0x12, 0x2d, 0xaf, 0x4e, 0xb6,
	0x74, 0x82, 0x2d, 0x9d, 0x19, 0x8c, 0x84, 0xd6, 0x52, 0xe3, 0x87, 0x3d, 0xe4, 0x5e, 0xc4, 0x9f,
	0x02, 0x38, 0x7d, 0x8f, 0x23, 0x71, 0x4f, 0xf6, 0xbf, 0x90, 0xa5, 0x14, 0x86, 0xe5, 0xf2, 0xaa,
	0xc4, 0x7f, 0x35, 0xe4, 0x18, 0x3b, 0xda, 0xfb, 0x10, 0xfe, 0x15, 0xed, 0xc5, 0x17, 0x02, 0x13,
	0xf7, 0x88, 0xb7, 0xfe, 0x3a, 0xa0, 0x6f, 0x00, 0x76, 0x53, 0x46, 0x69, 0xda, 0xfb, 0xc7, 0xe7,
	0x67, 0x69, 0x7f, 0x0c, 0xe3, 0xf9, 0xc7, 0x6f, 0xdf, 0x3f, 0x0f, 0x66, 0xf1, 0x49, 0x76, 0xf7,
	0x2c, 0x73, 0xf7, 0x4b, 0xe6, 0xcf, 0xa3, 0x4b, 0x72, 0xe1, 0xb6, 0xdc, 0xb5, 0x42, 0x69, 0xda,
	0x1b, 0xae, 0xf9, 0x59, 0xda, 0xef, 0xf5, 0x37, 0x5b, 0xfa, 0x83, 0xea, 0x92, 0x5c, 0x2c, 0xc7,
	0x78, 0x8e, 0x3d, 0xff, 0x19, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xcb, 0x97, 0x62, 0xcb, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post-service.proto",
}
