// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post-service.proto

package post_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	CustomerId           int64                `protobuf:"varint,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string               `protobuf:"bytes,2,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               string               `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string               `protobuf:"bytes,4,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Product              string               `protobuf:"bytes,6,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string               `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string               `protobuf:"bytes,8,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64              `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string               `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo             `protobuf:"bytes,11,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32                `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            *timestamp.Timestamp `protobuf:"bytes,14,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	IsDelete             bool                 `protobuf:"varint,15,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *Post) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *Post) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Post) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Post) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Post) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *Post) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Post) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *Post) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *Post) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Post) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Post) GetUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedOn
	}
	return nil
}

func (m *Post) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type PostDetail struct {
	Api                  string               `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	PostId               string               `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Notes                string               `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo             `protobuf:"bytes,5,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32                `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	IsDelete             bool                 `protobuf:"varint,7,opt,name=isDelete,proto3" json:"isDelete,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            *timestamp.Timestamp `protobuf:"bytes,10,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PostDetail) Reset()         { *m = PostDetail{} }
func (m *PostDetail) String() string { return proto.CompactTextString(m) }
func (*PostDetail) ProtoMessage()    {}
func (*PostDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{1}
}

func (m *PostDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDetail.Unmarshal(m, b)
}
func (m *PostDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDetail.Marshal(b, m, deterministic)
}
func (m *PostDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDetail.Merge(m, src)
}
func (m *PostDetail) XXX_Size() int {
	return xxx_messageInfo_PostDetail.Size(m)
}
func (m *PostDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PostDetail proto.InternalMessageInfo

func (m *PostDetail) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *PostDetail) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostDetail) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PostDetail) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *PostDetail) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *PostDetail) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PostDetail) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

func (m *PostDetail) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *PostDetail) GetUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedOn
	}
	return nil
}

type Photo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Photo) Reset()         { *m = Photo{} }
func (m *Photo) String() string { return proto.CompactTextString(m) }
func (*Photo) ProtoMessage()    {}
func (*Photo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{2}
}

func (m *Photo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Photo.Unmarshal(m, b)
}
func (m *Photo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Photo.Marshal(b, m, deterministic)
}
func (m *Photo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Photo.Merge(m, src)
}
func (m *Photo) XXX_Size() int {
	return xxx_messageInfo_Photo.Size(m)
}
func (m *Photo) XXX_DiscardUnknown() {
	xxx_messageInfo_Photo.DiscardUnknown(m)
}

var xxx_messageInfo_Photo proto.InternalMessageInfo

func (m *Photo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Photo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreatePostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string   `protobuf:"bytes,5,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Product              string   `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string   `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64  `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string   `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,12,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,14,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{3}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePostRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *CreatePostRequest) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *CreatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreatePostRequest) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *CreatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePostRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *CreatePostRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreatePostRequest) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *CreatePostRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreatePostRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *CreatePostRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *CreatePostRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreatePostRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type CreatePostResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{4}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePostResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type UpdatePostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           int64    `protobuf:"varint,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	CustomerName         string   `protobuf:"bytes,3,opt,name=customerName,proto3" json:"customerName,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Chanel               string   `protobuf:"bytes,5,opt,name=chanel,proto3" json:"chanel,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Product              string   `protobuf:"bytes,7,opt,name=product,proto3" json:"product,omitempty"`
	Phone                string   `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Pic                  string   `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Price                float64  `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`
	Notes                string   `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,12,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,14,opt,name=api,proto3" json:"api,omitempty"`
	DbId                 string   `protobuf:"bytes,15,opt,name=dbId,proto3" json:"dbId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{5}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetCustomerId() int64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *UpdatePostRequest) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *UpdatePostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdatePostRequest) GetChanel() string {
	if m != nil {
		return m.Chanel
	}
	return ""
}

func (m *UpdatePostRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdatePostRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *UpdatePostRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdatePostRequest) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *UpdatePostRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdatePostRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *UpdatePostRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *UpdatePostRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePostRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

type UpdatePostResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Error                bool     `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{6}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type CreatePostDetailRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Notes                string   `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,4,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,6,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostDetailRequest) Reset()         { *m = CreatePostDetailRequest{} }
func (m *CreatePostDetailRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostDetailRequest) ProtoMessage()    {}
func (*CreatePostDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{7}
}

func (m *CreatePostDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostDetailRequest.Unmarshal(m, b)
}
func (m *CreatePostDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostDetailRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostDetailRequest.Merge(m, src)
}
func (m *CreatePostDetailRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostDetailRequest.Size(m)
}
func (m *CreatePostDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostDetailRequest proto.InternalMessageInfo

func (m *CreatePostDetailRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostDetailRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatePostDetailRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *CreatePostDetailRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *CreatePostDetailRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreatePostDetailRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type CreatePostDetailResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostDetailResponse) Reset()         { *m = CreatePostDetailResponse{} }
func (m *CreatePostDetailResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostDetailResponse) ProtoMessage()    {}
func (*CreatePostDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{8}
}

func (m *CreatePostDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostDetailResponse.Unmarshal(m, b)
}
func (m *CreatePostDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostDetailResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostDetailResponse.Merge(m, src)
}
func (m *CreatePostDetailResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostDetailResponse.Size(m)
}
func (m *CreatePostDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostDetailResponse proto.InternalMessageInfo

func (m *CreatePostDetailResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreatePostDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreatePostDetailResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type UpdatePostDetailRequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Notes                string   `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	Photo                []*Photo `protobuf:"bytes,4,rep,name=photo,proto3" json:"photo,omitempty"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Api                  string   `protobuf:"bytes,6,opt,name=api,proto3" json:"api,omitempty"`
	DbId                 string   `protobuf:"bytes,7,opt,name=dbId,proto3" json:"dbId,omitempty"`
	IsDeleted            bool     `protobuf:"varint,8,opt,name=isDeleted,proto3" json:"isDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostDetailRequest) Reset()         { *m = UpdatePostDetailRequest{} }
func (m *UpdatePostDetailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostDetailRequest) ProtoMessage()    {}
func (*UpdatePostDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{9}
}

func (m *UpdatePostDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostDetailRequest.Unmarshal(m, b)
}
func (m *UpdatePostDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostDetailRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostDetailRequest.Merge(m, src)
}
func (m *UpdatePostDetailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostDetailRequest.Size(m)
}
func (m *UpdatePostDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostDetailRequest proto.InternalMessageInfo

func (m *UpdatePostDetailRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *UpdatePostDetailRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdatePostDetailRequest) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

func (m *UpdatePostDetailRequest) GetPhoto() []*Photo {
	if m != nil {
		return m.Photo
	}
	return nil
}

func (m *UpdatePostDetailRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdatePostDetailRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostDetailRequest) GetDbId() string {
	if m != nil {
		return m.DbId
	}
	return ""
}

func (m *UpdatePostDetailRequest) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type UpdatePostDetailResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostDetailResponse) Reset()         { *m = UpdatePostDetailResponse{} }
func (m *UpdatePostDetailResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostDetailResponse) ProtoMessage()    {}
func (*UpdatePostDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{10}
}

func (m *UpdatePostDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostDetailResponse.Unmarshal(m, b)
}
func (m *UpdatePostDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostDetailResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostDetailResponse.Merge(m, src)
}
func (m *UpdatePostDetailResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostDetailResponse.Size(m)
}
func (m *UpdatePostDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostDetailResponse proto.InternalMessageInfo

func (m *UpdatePostDetailResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdatePostDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UpdatePostDetailResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type GetPostDataRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostDataRequest) Reset()         { *m = GetPostDataRequest{} }
func (m *GetPostDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostDataRequest) ProtoMessage()    {}
func (*GetPostDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{11}
}

func (m *GetPostDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostDataRequest.Unmarshal(m, b)
}
func (m *GetPostDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostDataRequest.Marshal(b, m, deterministic)
}
func (m *GetPostDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostDataRequest.Merge(m, src)
}
func (m *GetPostDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostDataRequest.Size(m)
}
func (m *GetPostDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostDataRequest proto.InternalMessageInfo

func (m *GetPostDataRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPostDataRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetPostDataResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Post                 *Post    `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Error                bool     `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostDataResponse) Reset()         { *m = GetPostDataResponse{} }
func (m *GetPostDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostDataResponse) ProtoMessage()    {}
func (*GetPostDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{12}
}

func (m *GetPostDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostDataResponse.Unmarshal(m, b)
}
func (m *GetPostDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostDataResponse.Marshal(b, m, deterministic)
}
func (m *GetPostDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostDataResponse.Merge(m, src)
}
func (m *GetPostDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostDataResponse.Size(m)
}
func (m *GetPostDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostDataResponse proto.InternalMessageInfo

func (m *GetPostDataResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetPostDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPostDataResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *GetPostDataResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type GetPostDataDetailRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostDataDetailRequest) Reset()         { *m = GetPostDataDetailRequest{} }
func (m *GetPostDataDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostDataDetailRequest) ProtoMessage()    {}
func (*GetPostDataDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{13}
}

func (m *GetPostDataDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostDataDetailRequest.Unmarshal(m, b)
}
func (m *GetPostDataDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostDataDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetPostDataDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostDataDetailRequest.Merge(m, src)
}
func (m *GetPostDataDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostDataDetailRequest.Size(m)
}
func (m *GetPostDataDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostDataDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostDataDetailRequest proto.InternalMessageInfo

func (m *GetPostDataDetailRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPostDataDetailRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetPostDataDetailResponse struct {
	Api                  string      `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PostDetail           *PostDetail `protobuf:"bytes,3,opt,name=postDetail,proto3" json:"postDetail,omitempty"`
	Error                bool        `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetPostDataDetailResponse) Reset()         { *m = GetPostDataDetailResponse{} }
func (m *GetPostDataDetailResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostDataDetailResponse) ProtoMessage()    {}
func (*GetPostDataDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{14}
}

func (m *GetPostDataDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostDataDetailResponse.Unmarshal(m, b)
}
func (m *GetPostDataDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostDataDetailResponse.Marshal(b, m, deterministic)
}
func (m *GetPostDataDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostDataDetailResponse.Merge(m, src)
}
func (m *GetPostDataDetailResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostDataDetailResponse.Size(m)
}
func (m *GetPostDataDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostDataDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostDataDetailResponse proto.InternalMessageInfo

func (m *GetPostDataDetailResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetPostDataDetailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetPostDataDetailResponse) GetPostDetail() *PostDetail {
	if m != nil {
		return m.PostDetail
	}
	return nil
}

func (m *GetPostDataDetailResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

type GetListPostDataRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListPostDataRequest) Reset()         { *m = GetListPostDataRequest{} }
func (m *GetListPostDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetListPostDataRequest) ProtoMessage()    {}
func (*GetListPostDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{15}
}

func (m *GetListPostDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListPostDataRequest.Unmarshal(m, b)
}
func (m *GetListPostDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListPostDataRequest.Marshal(b, m, deterministic)
}
func (m *GetListPostDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListPostDataRequest.Merge(m, src)
}
func (m *GetListPostDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetListPostDataRequest.Size(m)
}
func (m *GetListPostDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListPostDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListPostDataRequest proto.InternalMessageInfo

func (m *GetListPostDataRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetListPostDataRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetListPostDataResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Post                 []*Post  `protobuf:"bytes,3,rep,name=post,proto3" json:"post,omitempty"`
	Error                bool     `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListPostDataResponse) Reset()         { *m = GetListPostDataResponse{} }
func (m *GetListPostDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetListPostDataResponse) ProtoMessage()    {}
func (*GetListPostDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d05c9fd6a018b85, []int{16}
}

func (m *GetListPostDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListPostDataResponse.Unmarshal(m, b)
}
func (m *GetListPostDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListPostDataResponse.Marshal(b, m, deterministic)
}
func (m *GetListPostDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListPostDataResponse.Merge(m, src)
}
func (m *GetListPostDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetListPostDataResponse.Size(m)
}
func (m *GetListPostDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListPostDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListPostDataResponse proto.InternalMessageInfo

func (m *GetListPostDataResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetListPostDataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetListPostDataResponse) GetPost() []*Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *GetListPostDataResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func init() {
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*PostDetail)(nil), "PostDetail")
	proto.RegisterType((*Photo)(nil), "Photo")
	proto.RegisterType((*CreatePostRequest)(nil), "CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "CreatePostResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "UpdatePostResponse")
	proto.RegisterType((*CreatePostDetailRequest)(nil), "CreatePostDetailRequest")
	proto.RegisterType((*CreatePostDetailResponse)(nil), "CreatePostDetailResponse")
	proto.RegisterType((*UpdatePostDetailRequest)(nil), "UpdatePostDetailRequest")
	proto.RegisterType((*UpdatePostDetailResponse)(nil), "UpdatePostDetailResponse")
	proto.RegisterType((*GetPostDataRequest)(nil), "GetPostDataRequest")
	proto.RegisterType((*GetPostDataResponse)(nil), "GetPostDataResponse")
	proto.RegisterType((*GetPostDataDetailRequest)(nil), "GetPostDataDetailRequest")
	proto.RegisterType((*GetPostDataDetailResponse)(nil), "GetPostDataDetailResponse")
	proto.RegisterType((*GetListPostDataRequest)(nil), "GetListPostDataRequest")
	proto.RegisterType((*GetListPostDataResponse)(nil), "GetListPostDataResponse")
}

func init() { proto.RegisterFile("post-service.proto", fileDescriptor_3d05c9fd6a018b85) }

var fileDescriptor_3d05c9fd6a018b85 = []byte{
	// 967 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0x96, 0xed, 0x38, 0x89, 0xcb, 0xf3, 0xb3, 0xd3, 0x33, 0xda, 0x74, 0xcc, 0xc0, 0x5a, 0x7d,
	0x40, 0x61, 0xd1, 0x76, 0xc4, 0x20, 0x21, 0xb4, 0xe2, 0x04, 0x2b, 0xad, 0x46, 0x42, 0xb0, 0x98,
	0x9f, 0x13, 0x17, 0x8f, 0xdd, 0x3b, 0x6b, 0x91, 0xa4, 0x8d, 0xbb, 0x33, 0x0f, 0x00, 0x37, 0xae,
	0x3c, 0x09, 0x12, 0x37, 0x5e, 0x02, 0x89, 0x47, 0x80, 0x3b, 0xaf, 0x80, 0xba, 0xfd, 0x1f, 0xdb,
	0x19, 0x18, 0x56, 0x48, 0x48, 0x7b, 0x4b, 0x55, 0xff, 0x54, 0xd5, 0xf7, 0xd5, 0x57, 0xee, 0x00,
	0x4a, 0xb9, 0x90, 0x8f, 0x04, 0xcb, 0x6e, 0x92, 0x88, 0xd1, 0x34, 0xe3, 0x92, 0x7b, 0x0f, 0xae,
	0x39, 0xbf, 0x5e, 0xb1, 0xa5, 0xb6, 0xae, 0xb6, 0xcf, 0x97, 0x32, 0x59, 0x33, 0x21, 0xc3, 0x75,
	0x5a, 0x6c, 0x38, 0x2f, 0x36, 0x84, 0x69, 0xb2, 0x0c, 0x37, 0x1b, 0x2e, 0x43, 0x99, 0xf0, 0x8d,
	0xc8, 0x57, 0xc9, 0xaf, 0x16, 0x8c, 0x9e, 0x71, 0x21, 0xd1, 0x1b, 0x00, 0xd1, 0x56, 0x48, 0xbe,
	0x66, 0xd9, 0x65, 0x8c, 0x0d, 0xdf, 0x58, 0x58, 0x41, 0xc3, 0x83, 0x08, 0x1c, 0x94, 0xd6, 0x27,
	0xe1, 0x9a, 0x61, 0xd3, 0x37, 0x16, 0x4e, 0xd0, 0xf2, 0xa1, 0xfb, 0x30, 0xde, 0x0a, 0x7d, 0xde,
	0xd2, 0xab, 0x85, 0xa5, 0xfc, 0xd1, 0x8b, 0x70, 0xc3, 0x56, 0x78, 0x94, 0xfb, 0x73, 0x0b, 0xf9,
	0xe0, 0xc6, 0x4c, 0x44, 0x59, 0x92, 0xaa, 0x94, 0xb0, 0xad, 0x17, 0x9b, 0x2e, 0x84, 0x61, 0x92,
	0x66, 0x3c, 0xde, 0x46, 0x12, 0x8f, 0xf5, 0x6a, 0x69, 0xa2, 0x33, 0xb0, 0xd3, 0x17, 0x7c, 0xc3,
	0xf0, 0x44, 0xfb, 0x73, 0x03, 0xdd, 0x03, 0x2b, 0x4d, 0x22, 0x3c, 0xd5, 0x3e, 0xf5, 0x53, 0xef,
	0xcb, 0x92, 0x88, 0x61, 0xc7, 0x37, 0x16, 0x46, 0x90, 0x1b, 0xca, 0xbb, 0xe1, 0x92, 0x09, 0x0c,
	0xf9, 0x69, 0x6d, 0xa0, 0x73, 0x7d, 0xa7, 0xe4, 0xd8, 0xf5, 0xad, 0x85, 0x7b, 0x31, 0xa6, 0xcf,
	0x94, 0x15, 0xe4, 0x4e, 0x55, 0x85, 0x90, 0xa1, 0xdc, 0x0a, 0x7c, 0xe0, 0x1b, 0x0b, 0x3b, 0x28,
	0x2c, 0xf4, 0x3e, 0x38, 0x51, 0xc6, 0x42, 0xc9, 0xe2, 0x4f, 0x37, 0xf8, 0xd0, 0x37, 0x16, 0xee,
	0x85, 0x47, 0x73, 0xd0, 0x69, 0xc9, 0x0a, 0xfd, 0xa2, 0x64, 0x25, 0xa8, 0x37, 0xab, 0x93, 0xdb,
	0x34, 0x2e, 0x4e, 0x1e, 0xdd, 0x7e, 0xb2, 0xda, 0x8c, 0x3c, 0x98, 0x26, 0xe2, 0x09, 0x5b, 0x31,
	0xc9, 0xf0, 0xb1, 0x6f, 0x2c, 0xa6, 0x41, 0x65, 0x93, 0x9f, 0x4d, 0x00, 0x45, 0xe9, 0x13, 0x26,
	0xc3, 0x64, 0xa5, 0x20, 0x09, 0xd3, 0x44, 0x33, 0xea, 0x04, 0xea, 0xa7, 0x2a, 0x44, 0x35, 0xd2,
	0x65, 0x5c, 0x90, 0x58, 0x58, 0xbb, 0x74, 0x58, 0x5d, 0x3a, 0x2a, 0xd8, 0x46, 0xbd, 0xb0, 0xd9,
	0xfb, 0x61, 0x1b, 0xb7, 0x60, 0x6b, 0x96, 0x30, 0x69, 0x97, 0xd0, 0x86, 0xd4, 0xb9, 0x33, 0xa4,
	0xf0, 0x0f, 0x20, 0x25, 0x6f, 0x81, 0xad, 0xf3, 0x46, 0x47, 0x60, 0x26, 0xa5, 0x02, 0xcc, 0x24,
	0x56, 0x00, 0x6e, 0xb3, 0x55, 0x81, 0x95, 0xfa, 0x49, 0xfe, 0x34, 0xe1, 0xe4, 0x23, 0x1d, 0x52,
	0xe1, 0x1c, 0xb0, 0x6f, 0xb7, 0x4c, 0xc8, 0xce, 0xb9, 0xb6, 0xa2, 0xcc, 0x5b, 0x15, 0x65, 0xed,
	0x55, 0xd4, 0x68, 0x40, 0x51, 0xf6, 0x3e, 0x45, 0x8d, 0xf7, 0x2a, 0x6a, 0x32, 0xa0, 0xa8, 0x69,
	0x8f, 0xa2, 0x9c, 0x1e, 0x45, 0x41, 0xaf, 0xa2, 0xdc, 0xde, 0xd6, 0x38, 0xd8, 0xdf, 0x1a, 0x87,
	0xad, 0xd6, 0x28, 0x5a, 0xf6, 0xa8, 0x6a, 0x59, 0xf2, 0x15, 0xa0, 0x26, 0xe0, 0x22, 0xe5, 0x1b,
	0xc1, 0x7a, 0x5a, 0x1b, 0xc3, 0x64, 0xcd, 0x84, 0x08, 0xaf, 0xcb, 0x01, 0x55, 0x9a, 0x2a, 0x3f,
	0x96, 0x65, 0x3c, 0xd3, 0x30, 0x4f, 0x83, 0xdc, 0x20, 0xdf, 0x5b, 0x70, 0xf2, 0xa5, 0x6e, 0x81,
	0x57, 0x4c, 0xfe, 0x27, 0x4c, 0x22, 0x04, 0xa3, 0xf8, 0xea, 0x32, 0xd6, 0x53, 0xcb, 0x09, 0xf4,
	0x6f, 0xf2, 0x1c, 0x50, 0x93, 0x84, 0x3b, 0xb0, 0x9b, 0x33, 0x66, 0x55, 0x8c, 0x55, 0x6c, 0x8f,
	0x9a, 0x6c, 0xff, 0x64, 0xc0, 0xac, 0x6e, 0xa3, 0x7c, 0x3e, 0x96, 0x9c, 0xd7, 0x43, 0xd1, 0xd8,
	0x37, 0x14, 0xcd, 0x3d, 0x43, 0xd1, 0xea, 0xc5, 0x6b, 0xb4, 0x1f, 0x2f, 0xbb, 0x0f, 0xaf, 0x71,
	0xdd, 0xf9, 0x5f, 0x03, 0xee, 0xa6, 0xfc, 0xd2, 0xfa, 0xff, 0x77, 0x03, 0x66, 0x35, 0xf4, 0xff,
	0x0b, 0x44, 0xaa, 0x0e, 0x9a, 0xd4, 0x1d, 0x84, 0xce, 0xc1, 0x29, 0x3f, 0x1e, 0xb1, 0xee, 0xfa,
	0x69, 0x50, 0x3b, 0x14, 0x86, 0xdd, 0x22, 0x5f, 0x1a, 0x86, 0xef, 0x01, 0x7a, 0xca, 0xa4, 0xbe,
	0x3a, 0x94, 0x61, 0x77, 0x86, 0x38, 0xe5, 0x57, 0x44, 0xc5, 0x31, 0x6b, 0x66, 0x33, 0x38, 0x6d,
	0x9d, 0xbb, 0x43, 0x42, 0x73, 0x18, 0x29, 0x52, 0x74, 0x3e, 0xee, 0x85, 0x4d, 0xb5, 0x7e, 0xb4,
	0x6b, 0x40, 0x01, 0x1f, 0x00, 0x6e, 0xc4, 0x6c, 0xf3, 0x7d, 0x7b, 0xc6, 0x3f, 0x18, 0x30, 0xef,
	0x39, 0x7e, 0x87, 0xc4, 0xdf, 0x06, 0x48, 0x2b, 0x2e, 0x8a, 0xf4, 0x5d, 0xda, 0xa0, 0xa7, 0xb1,
	0x3c, 0x50, 0xca, 0x87, 0x70, 0xff, 0x29, 0x93, 0x1f, 0x27, 0xa2, 0x03, 0x7d, 0x3d, 0x6a, 0x8d,
	0xd6, 0xa8, 0xed, 0x16, 0x74, 0x03, 0xb3, 0xce, 0x1d, 0xff, 0x8a, 0x06, 0xeb, 0x6f, 0xd1, 0x70,
	0xf1, 0x8b, 0x0d, 0xae, 0xda, 0xf4, 0x79, 0xfe, 0x94, 0x47, 0x9f, 0x01, 0xd4, 0x22, 0x47, 0x88,
	0x76, 0x1e, 0x17, 0xde, 0x29, 0xed, 0x7e, 0xff, 0x88, 0xf7, 0xdd, 0x6f, 0x7f, 0xfc, 0x68, 0x9e,
	0x91, 0xe3, 0xe5, 0xcd, 0x3b, 0x4b, 0x15, 0x6e, 0x99, 0x3f, 0x84, 0x1e, 0x1b, 0x0f, 0xd5, 0x95,
	0x75, 0xcf, 0x23, 0x44, 0x3b, 0x5f, 0x39, 0xef, 0x94, 0x76, 0x87, 0x6e, 0xcf, 0x95, 0xf9, 0x0b,
	0x49, 0x5d, 0xc9, 0xe1, 0xde, 0xee, 0x28, 0x42, 0x98, 0x0e, 0x0c, 0x54, 0x6f, 0x4e, 0x87, 0xe6,
	0x16, 0x79, 0x53, 0x07, 0xf1, 0xc9, 0x6b, 0x3b, 0x79, 0x3f, 0xd2, 0xff, 0x6f, 0x62, 0xbd, 0xb9,
	0x08, 0xb8, 0xab, 0x5b, 0x84, 0xe9, 0xc0, 0xbc, 0xf2, 0xe6, 0x74, 0x48, 0xe4, 0x3d, 0x01, 0xf3,
	0xaa, 0x76, 0x03, 0x06, 0xe0, 0x36, 0xfa, 0x1b, 0x9d, 0xd2, 0xae, 0xb0, 0xbd, 0x33, 0xda, 0xa3,
	0x5a, 0x82, 0x75, 0x04, 0x44, 0x0e, 0xab, 0x08, 0x71, 0x28, 0x43, 0x75, 0xe7, 0x37, 0x70, 0xd2,
	0xd1, 0x0c, 0x9a, 0xd3, 0x21, 0x19, 0x7a, 0x1e, 0x1d, 0x94, 0x18, 0x79, 0xa0, 0xa3, 0xcc, 0xc9,
	0x59, 0x19, 0xa5, 0xc8, 0xbd, 0x0a, 0x16, 0xc1, 0xf1, 0x4e, 0x43, 0xa3, 0x19, 0xed, 0x97, 0x89,
	0x87, 0xe9, 0x40, 0xef, 0x93, 0xd7, 0x75, 0x98, 0x19, 0x41, 0xad, 0x62, 0x96, 0xab, 0x44, 0xc8,
	0xc7, 0xc6, 0xc3, 0xab, 0xb1, 0x7e, 0x48, 0xbf, 0xfb, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18,
	0x1e, 0xc8, 0xae, 0x8f, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	CreatePostDetail(ctx context.Context, in *CreatePostDetailRequest, opts ...grpc.CallOption) (*CreatePostDetailResponse, error)
	UpdatePostDetail(ctx context.Context, in *UpdatePostDetailRequest, opts ...grpc.CallOption) (*UpdatePostDetailResponse, error)
	GetPostData(ctx context.Context, in *GetPostDataRequest, opts ...grpc.CallOption) (*GetPostDataResponse, error)
	GetPostDataDetail(ctx context.Context, in *GetPostDataDetailRequest, opts ...grpc.CallOption) (*GetPostDataDetailResponse, error)
	GetListPostData(ctx context.Context, in *GetListPostDataRequest, opts ...grpc.CallOption) (*GetListPostDataResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreatePostDetail(ctx context.Context, in *CreatePostDetailRequest, opts ...grpc.CallOption) (*CreatePostDetailResponse, error) {
	out := new(CreatePostDetailResponse)
	err := c.cc.Invoke(ctx, "/PostService/CreatePostDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePostDetail(ctx context.Context, in *UpdatePostDetailRequest, opts ...grpc.CallOption) (*UpdatePostDetailResponse, error) {
	out := new(UpdatePostDetailResponse)
	err := c.cc.Invoke(ctx, "/PostService/UpdatePostDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostData(ctx context.Context, in *GetPostDataRequest, opts ...grpc.CallOption) (*GetPostDataResponse, error) {
	out := new(GetPostDataResponse)
	err := c.cc.Invoke(ctx, "/PostService/GetPostData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostDataDetail(ctx context.Context, in *GetPostDataDetailRequest, opts ...grpc.CallOption) (*GetPostDataDetailResponse, error) {
	out := new(GetPostDataDetailResponse)
	err := c.cc.Invoke(ctx, "/PostService/GetPostDataDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetListPostData(ctx context.Context, in *GetListPostDataRequest, opts ...grpc.CallOption) (*GetListPostDataResponse, error) {
	out := new(GetListPostDataResponse)
	err := c.cc.Invoke(ctx, "/PostService/GetListPostData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	CreatePostDetail(context.Context, *CreatePostDetailRequest) (*CreatePostDetailResponse, error)
	UpdatePostDetail(context.Context, *UpdatePostDetailRequest) (*UpdatePostDetailResponse, error)
	GetPostData(context.Context, *GetPostDataRequest) (*GetPostDataResponse, error)
	GetPostDataDetail(context.Context, *GetPostDataDetailRequest) (*GetPostDataDetailResponse, error)
	GetListPostData(context.Context, *GetListPostDataRequest) (*GetListPostDataResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedPostServiceServer) CreatePostDetail(ctx context.Context, req *CreatePostDetailRequest) (*CreatePostDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePostDetail not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePostDetail(ctx context.Context, req *UpdatePostDetailRequest) (*UpdatePostDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePostDetail not implemented")
}
func (*UnimplementedPostServiceServer) GetPostData(ctx context.Context, req *GetPostDataRequest) (*GetPostDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostData not implemented")
}
func (*UnimplementedPostServiceServer) GetPostDataDetail(ctx context.Context, req *GetPostDataDetailRequest) (*GetPostDataDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDataDetail not implemented")
}
func (*UnimplementedPostServiceServer) GetListPostData(ctx context.Context, req *GetListPostDataRequest) (*GetListPostDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListPostData not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreatePostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/CreatePostDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePostDetail(ctx, req.(*CreatePostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/UpdatePostDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePostDetail(ctx, req.(*UpdatePostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/GetPostData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostData(ctx, req.(*GetPostDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostDataDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDataDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostDataDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/GetPostDataDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostDataDetail(ctx, req.(*GetPostDataDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetListPostData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListPostDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetListPostData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/GetListPostData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetListPostData(ctx, req.(*GetListPostDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "CreatePostDetail",
			Handler:    _PostService_CreatePostDetail_Handler,
		},
		{
			MethodName: "UpdatePostDetail",
			Handler:    _PostService_UpdatePostDetail_Handler,
		},
		{
			MethodName: "GetPostData",
			Handler:    _PostService_GetPostData_Handler,
		},
		{
			MethodName: "GetPostDataDetail",
			Handler:    _PostService_GetPostDataDetail_Handler,
		},
		{
			MethodName: "GetListPostData",
			Handler:    _PostService_GetListPostData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post-service.proto",
}
